# Terraform only creates the container. No aws_secretsmanager_secret_version,
# so a value never ends up in state. The first value comes from the rotation
# lambda.

resource "aws_secretsmanager_secret" "app" {
  # checkov:skip=CKV2_AWS_57: rotation is configured in rotation.tf
  name                    = local.secret_name
  description             = "demo app api key, value generated by rotation"
  kms_key_id              = aws_kms_key.secrets.arn
  recovery_window_in_days = 7
}

locals {
  # who may call GetSecretValue at all
  secret_readers = [
    aws_iam_role.app_secret_reader.arn,
    var.admin_principal_arn, # lockout exception, but has no kms:Decrypt so can't actually read the value
  ]
}

# Careful editing this: the deny statements also apply to whoever runs
# terraform, which is why the admin is excluded from them. Remove that
# exception and you can lock yourself out of the secret.
data "aws_iam_policy_document" "secret" {
  statement {
    sid       = "OnlyKnownReaders"
    effect    = "Deny"
    actions   = ["secretsmanager:GetSecretValue"]
    resources = ["*"]
    principals {
      type        = "*"
      identifiers = ["*"]
    }
    condition {
      test     = "StringNotEquals"
      variable = "aws:PrincipalArn"
      values   = local.secret_readers
    }
  }

  # data plane only through the vpc endpoint. admin exempt so terraform works
  # from my laptop; AWS services acting as themselves are exempt since they
  # never come through the endpoint (nothing here allows them to read anyway).
  statement {
    sid    = "OnlyThroughVpce"
    effect = "Deny"
    actions = [
      "secretsmanager:GetSecretValue",
      "secretsmanager:PutSecretValue",
      "secretsmanager:UpdateSecretVersionStage",
    ]
    resources = ["*"]
    principals {
      type        = "*"
      identifiers = ["*"]
    }
    condition {
      test     = "StringNotEquals"
      variable = "aws:SourceVpce"
      values   = [aws_vpc_endpoint.secretsmanager.id]
    }
    condition {
      test     = "StringNotEquals"
      variable = "aws:PrincipalArn"
      values   = [var.admin_principal_arn]
    }
    condition {
      test     = "Bool"
      variable = "aws:PrincipalIsAWSService"
      values   = ["false"]
    }
  }

  statement {
    sid    = "OnlyAdminChangesPolicy"
    effect = "Deny"
    actions = [
      "secretsmanager:DeleteResourcePolicy",
      "secretsmanager:PutResourcePolicy",
    ]
    resources = ["*"]
    principals {
      type        = "*"
      identifiers = ["*"]
    }
    condition {
      test     = "StringNotEquals"
      variable = "aws:PrincipalArn"
      values   = [var.admin_principal_arn]
    }
  }
}

resource "aws_secretsmanager_secret_policy" "app" {
  secret_arn          = aws_secretsmanager_secret.app.arn
  policy              = data.aws_iam_policy_document.secret.json
  block_public_policy = true
}
